import type { Metadata } from 'next';
import { Kode_Mono } from 'next/font/google';
import './globals.css';
import { ScreenProvider } from './context/ScreenContext';
import Footer from './components/Footer';

const KodeMono = Kode_Mono({
  variable: '--font-kode-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Future Racing',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${KodeMono.variable}`}>
        <ScreenProvider>{children}</ScreenProvider>
        <Footer />
      </body>
    </html>
  );
}

/*

align-items center
box-sizing border-box
color rgb(34, 34, 34)
color-scheme dark
column-gap 64px
display grid
font-family "Kode Mono", "Kode Mono Fallback"
font-size 12px
grid-template-rows 20px 564px 20px
height 844px
justify-items center
margin-bottom 0px
margin-left 0px
margin-right 0px
margin-top 0px
min-height 844px
padding-bottom 80px
padding-left 32px
padding-right 32px
padding-top 32px
row-gap 64px
unicode-bidi isolate
width 390px
-webkit-font-smoothing antialiased


background-attachment fixed
background-clip border-box
background-color rgb(10, 10, 10)
background-image url(http://localhost:3000/Clouds.svg)
background-origin padding-box
background-position-x 50%
background-position-y 50%
background-repeat no-repeat
background-size cover
box-sizing border-box
color rgb(34, 34, 34)
color-scheme dark
display block
font-family Arial
font-size 12px
height 844px
margin-bottom 0px
margin-left 0px
margin-right 0px
margin-top 0px
max-width 390px
overflow-x hidden
padding-bottom 0px
padding-left 0px
padding-right 0px
padding-top 0px
width 390px
-webkit-font-smoothing antialiased

*/
