import type { Metadata } from "next";
import {  Kode_Mono } from "next/font/google";
import "./globals.css";
import Head from "next/head";
import IconContainer from "./IconContainer";

const KodeMono = Kode_Mono({
  variable: "--font-kode-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Future Racing",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
         <link
            href="https://fonts.googleapis.com/css2?family=Kode+Mono&display=swap"
            rel="stylesheet"
          />
      </Head>
      <body className={`${KodeMono.variable}`}>
        <IconContainer />
        {children}
      </body>
    </html>
  );
}
